import { movesByCharacter } from '../config/movesConfig.js';

export const characters = {
  guardian: {
    id: 'guardian',
    name: 'Guardião',
    archetype: 'guardian',
    selectable: true,
    moves: movesByCharacter.guardian,
    aiProfile: 'guardian',
    info: {
      style: 'Técnico · fundamentos',
      saberName: 'Ciano-gelo',
      trait: 'Bloqueio custa menos stamina',
      ability: 'Contraguarda: postura curta que responde com a riposta',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Azul-profundo', color: '#5f8bff', challenge: null },
      { id: 'challenge', name: 'Verde-água', color: '#3fffc8', challenge: { stat: 'perfectParries', target: 3, text: 'vença com 3 parries perfeitos' } },
    ],
    sound: {
      humFrequency: 74,
    },
    appearance: {
      cloakColor: '#6b5a48',
      bodyColor: '#2e2925',
      trimColor: '#8c7860',
      saberColor: '#7fe4ff',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 3,
      guardAngleDegrees: -60,
      bladeLength: 92,
      hiltScale: 1,
      bladeWidthScale: 1,
      scarf: false,
      dualBlade: null,
    },
  },
  shadow: {
    id: 'shadow',
    name: 'Sombra',
    archetype: 'shadow',
    selectable: true,
    moves: movesByCharacter.shadow,
    aiProfile: 'shadow',
    info: {
      style: 'Agressiva · pressão',
      saberName: 'Magenta',
      trait: 'Golpe que acerta devolve stamina',
      ability: 'Ímpeto: avanço com armadura contra um golpe',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Violeta-escuro', color: '#c23cff', challenge: null },
      { id: 'challenge', name: 'Rubi', color: '#ff2a3a', challenge: { stat: 'damage', target: 200, text: 'vença causando 200 de dano' } },
    ],
    sound: {
      humFrequency: 62,
    },
    appearance: {
      cloakColor: '#1f2029',
      bodyColor: '#121319',
      trimColor: '#2c2e3a',
      saberColor: '#ff3f9e',
      hoodUp: true,
      longCape: true,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 10,
      guardAngleDegrees: 25,
      bladeLength: 92,
      hiltScale: 1,
      bladeWidthScale: 1,
      scarf: false,
      dualBlade: null,
    },
  },
  bastion: {
    id: 'bastion',
    name: 'Bastião',
    archetype: 'bastion',
    selectable: true,
    moves: movesByCharacter.bastion,
    aiProfile: 'bastion',
    info: {
      style: 'Tanque · peso',
      saberName: 'Verde-ácido',
      trait: 'Anda bloqueando e não é empurrado',
      ability: 'Marreta: golpe lento com armadura contra dois golpes',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Ouro-pálido', color: '#ffe08a', challenge: null },
      { id: 'challenge', name: 'Azul-céu', color: '#3fd0ff', challenge: { stat: 'blocks', target: 12, text: 'vença com 12 defesas' } },
    ],
    sound: {
      humFrequency: 52,
    },
    appearance: {
      cloakColor: '#3d4636',
      bodyColor: '#1f231c',
      trimColor: '#5a6650',
      saberColor: '#9dff3f',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: true,
      shoulderScale: 1.45,
      torsoLeanDegrees: 2,
      guardAngleDegrees: -15,
      bladeLength: 100,
      hiltScale: 1,
      bladeWidthScale: 1.4,
      scarf: false,
      dualBlade: null,
    },
  },
  wasp: {
    id: 'wasp',
    name: 'Vespa',
    archetype: 'wasp',
    selectable: true,
    moves: movesByCharacter.wasp,
    aiProfile: 'wasp',
    info: {
      style: 'Velocidade · sequências',
      saberName: 'Amarelo-âmbar',
      trait: 'Sequência de cinco golpes rápidos',
      ability: 'Zumbido: avanço que atravessa o oponente',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Lima', color: '#7cff6b', challenge: null },
      { id: 'challenge', name: 'Rosa', color: '#ff6bd5', challenge: { stat: 'longestChain', target: 5, text: 'vença acertando a sequência completa de 5' } },
    ],
    sound: {
      humFrequency: 96,
    },
    appearance: {
      cloakColor: '#5c4a33',
      bodyColor: '#2a2219',
      trimColor: '#7a6446',
      saberColor: '#ffd23f',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 0.9,
      torsoLeanDegrees: 16,
      guardAngleDegrees: 40,
      bladeLength: 64,
      hiltScale: 1,
      bladeWidthScale: 0.85,
      scarf: false,
      dualBlade: { angleOffsetDegrees: 135, lengthScale: 0.85, offsetX: -0.1, offsetY: 0.02 },
    },
  },
  mirror: {
    id: 'mirror',
    name: 'Espelho',
    archetype: 'mirror',
    selectable: true,
    moves: movesByCharacter.mirror,
    aiProfile: 'mirror',
    info: {
      style: 'Defensivo · parry',
      saberName: 'Branco-prata',
      trait: 'Janelas de parry maiores',
      ability: 'Postura de Espera: apara e responde com a riposta',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Prata-azulada', color: '#9fd8ff', challenge: null },
      { id: 'challenge', name: 'Marfim', color: '#ffe2b0', challenge: { stat: 'perfectParries', target: 4, text: 'vença com 4 parries perfeitos' } },
    ],
    sound: {
      humFrequency: 84,
    },
    appearance: {
      cloakColor: '#b9bcc7',
      bodyColor: '#3a3d47',
      trimColor: '#e3e6ee',
      saberColor: '#e8eeff',
      hoodUp: true,
      longCape: true,
      masked: true,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 0,
      guardAngleDegrees: -90,
      bladeLength: 96,
      hiltScale: 1,
      bladeWidthScale: 1,
      scarf: false,
      dualBlade: null,
    },
  },
  haste: {
    id: 'haste',
    name: 'Haste',
    archetype: 'haste',
    selectable: true,
    moves: movesByCharacter.haste,
    aiProfile: 'haste',
    info: {
      style: 'Alcance · controle de distância',
      saberName: 'Violeta',
      trait: 'A ponta da lâmina dá mais dano; de perto, menos',
      ability: 'Varredura: golpe de alcance enorme e lento',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Anil', color: '#6b7cff', challenge: null },
      { id: 'challenge', name: 'Fúcsia', color: '#ff6bff', challenge: { stat: 'hits', target: 15, text: 'vença com 15 golpes acertados' } },
    ],
    sound: {
      humFrequency: 68,
    },
    appearance: {
      cloakColor: '#3b3348',
      bodyColor: '#1c1924',
      trimColor: '#564a68',
      saberColor: '#a46bff',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 0.95,
      torsoLeanDegrees: 2,
      guardAngleDegrees: -25,
      bladeLength: 104,
      hiltScale: 3.4,
      bladeWidthScale: 0.9,
      scarf: false,
      dualBlade: null,
    },
  },
  ember: {
    id: 'ember',
    name: 'Brasa',
    archetype: 'ember',
    selectable: true,
    moves: movesByCharacter.ember,
    aiProfile: 'ember',
    info: {
      style: 'Contra-ataque · leitura',
      saberName: 'Laranja-brasa',
      trait: 'Mais dano em quem está aberto',
      ability: 'Brasa Viva: postura que responde com um corte forte',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Ouro', color: '#ffcf3f', challenge: null },
      { id: 'challenge', name: 'Carmim', color: '#ff3f5a', challenge: { stat: 'counters', target: 3, text: 'vença com 3 contra-golpes da postura' } },
    ],
    sound: {
      humFrequency: 80,
    },
    appearance: {
      cloakColor: '#5a2c1e',
      bodyColor: '#24140f',
      trimColor: '#7a3e2a',
      saberColor: '#ff7a2a',
      hoodUp: true,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 12,
      guardAngleDegrees: 115,
      bladeLength: 86,
      hiltScale: 1,
      bladeWidthScale: 1,
      scarf: false,
      dualBlade: null,
    },
  },
  forge: {
    id: 'forge',
    name: 'Forja',
    archetype: 'forge',
    selectable: true,
    moves: movesByCharacter.forge,
    aiProfile: 'forge',
    info: {
      style: 'Pesada · carga',
      saberName: 'Vermelho-forja',
      trait: 'Empurra mais longe a cada golpe',
      ability: 'Forja: segure para carregar; o nível 3 quebra a guarda',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Laranja-forno', color: '#ff9a3f', challenge: null },
      { id: 'challenge', name: 'Verde-escória', color: '#b0ff3f', challenge: { stat: 'guardBreaks', target: 2, text: 'vença quebrando a guarda 2 vezes' } },
    ],
    sound: {
      humFrequency: 58,
    },
    appearance: {
      cloakColor: '#4a3a30',
      bodyColor: '#211a15',
      trimColor: '#6b5444',
      saberColor: '#ff4038',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 1.3,
      torsoLeanDegrees: 6,
      guardAngleDegrees: -40,
      bladeLength: 96,
      hiltScale: 1.3,
      bladeWidthScale: 1.7,
      scarf: false,
      dualBlade: null,
    },
  },
  heron: {
    id: 'heron',
    name: 'Garça',
    archetype: 'heron',
    selectable: true,
    moves: movesByCharacter.heron,
    aiProfile: 'heron',
    info: {
      style: 'Acrobática · mobilidade',
      saberName: 'Verde-menta',
      trait: 'Pula na parede, esquiva atravessando e tem dois aéreos',
      ability: 'Voo da Garça: salto que passa por cima do oponente',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Azul-gelo', color: '#a6e8ff', challenge: null },
      { id: 'challenge', name: 'Coral', color: '#ff8a6b', challenge: { stat: 'airHits', target: 4, text: 'vença acertando 4 ataques aéreos' } },
    ],
    sound: {
      humFrequency: 90,
    },
    appearance: {
      cloakColor: '#2f4a52',
      bodyColor: '#16232a',
      trimColor: '#7fa8b4',
      saberColor: '#5fffc0',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 0.85,
      torsoLeanDegrees: 9,
      guardAngleDegrees: -120,
      bladeLength: 86,
      hiltScale: 1,
      bladeWidthScale: 0.9,
      scarf: true,
      dualBlade: null,
    },
  },
  echo: {
    id: 'echo',
    name: 'Eco',
    archetype: 'echo',
    selectable: true,
    moves: movesByCharacter.echo,
    aiProfile: 'echo',
    info: {
      style: 'Trapaceira · fintas',
      saberName: 'Rosa-pálido',
      trait: 'Finta: tocar a guarda cancela o forte',
      ability: 'Passo-reflexo: passo curto e invulnerável',
    },
    altSaberColors: [
      { id: 'arcade', name: 'Lilás', color: '#c9a6ff', challenge: null },
      { id: 'challenge', name: 'Prata', color: '#d6dbe6', challenge: { stat: 'feints', target: 5, text: 'vença fintando 5 vezes' } },
    ],
    sound: {
      humFrequency: 88,
    },
    appearance: {
      cloakColor: '#23202b',
      bodyColor: '#121017',
      trimColor: '#c8c2d6',
      saberColor: '#ffa6e0',
      hoodUp: true,
      longCape: false,
      masked: true,
      pauldrons: false,
      shoulderScale: 0.9,
      torsoLeanDegrees: 6,
      guardAngleDegrees: 55,
      bladeLength: 88,
      hiltScale: 1,
      bladeWidthScale: 1,
      scarf: false,
      dualBlade: null,
    },
  },
  shadowAwakened: {
    id: 'shadowAwakened',
    name: 'Sombra Desperta',
    archetype: 'shadowAwakened',
    selectable: false,
    moves: movesByCharacter.shadow,
    aiProfile: 'shadow',
    info: {
      style: 'Chefe',
      saberName: 'Magenta',
      trait: 'Golpe que acerta devolve stamina',
      ability: 'Ímpeto: avanço com armadura contra um golpe',
    },
    altSaberColors: [],
    sound: {
      humFrequency: 55,
    },
    appearance: {
      cloakColor: '#14141c',
      bodyColor: '#0a0a0f',
      trimColor: '#3a1030',
      saberColor: '#ff3f9e',
      hoodUp: true,
      longCape: true,
      masked: false,
      pauldrons: true,
      shoulderScale: 1.2,
      torsoLeanDegrees: 12,
      guardAngleDegrees: 25,
      bladeLength: 98,
      hiltScale: 1,
      bladeWidthScale: 1.25,
      scarf: false,
      dualBlade: null,
    },
  },
};
