import { movesByCharacter } from '../config/movesConfig.js';

export const characters = {
  guardian: {
    id: 'guardian',
    name: 'Guardião',
    archetype: 'guardian',
    selectable: true,
    moves: movesByCharacter.guardian,
    aiProfile: 'guardian',
    info: {
      style: 'Técnico · fundamentos',
      trait: 'Bloqueio custa menos stamina',
      ability: 'Contraguarda: postura curta que responde com a riposta',
    },
    sound: {
      humFrequency: 74,
    },
    appearance: {
      cloakColor: '#6b5a48',
      bodyColor: '#2e2925',
      trimColor: '#8c7860',
      saberColor: '#7fe4ff',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 3,
      guardAngleDegrees: -60,
      bladeLength: 92,
      hiltScale: 1,
      bladeWidthScale: 1,
      dualBlade: null,
    },
  },
  shadow: {
    id: 'shadow',
    name: 'Sombra',
    archetype: 'shadow',
    selectable: true,
    moves: movesByCharacter.shadow,
    aiProfile: 'shadow',
    info: {
      style: 'Agressiva · pressão',
      trait: 'Golpe que acerta devolve stamina',
      ability: 'Ímpeto: avanço com armadura contra um golpe',
    },
    sound: {
      humFrequency: 62,
    },
    appearance: {
      cloakColor: '#1f2029',
      bodyColor: '#121319',
      trimColor: '#2c2e3a',
      saberColor: '#ff3f9e',
      hoodUp: true,
      longCape: true,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 10,
      guardAngleDegrees: 25,
      bladeLength: 92,
      hiltScale: 1,
      bladeWidthScale: 1,
      dualBlade: null,
    },
  },
  bastion: {
    id: 'bastion',
    name: 'Bastião',
    archetype: 'bastion',
    selectable: true,
    moves: movesByCharacter.bastion,
    aiProfile: 'bastion',
    info: {
      style: 'Tanque · peso',
      trait: 'Anda bloqueando e não é empurrado',
      ability: 'Marreta: golpe lento com armadura contra dois golpes',
    },
    sound: {
      humFrequency: 52,
    },
    appearance: {
      cloakColor: '#3d4636',
      bodyColor: '#1f231c',
      trimColor: '#5a6650',
      saberColor: '#9dff3f',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: true,
      shoulderScale: 1.45,
      torsoLeanDegrees: 2,
      guardAngleDegrees: -15,
      bladeLength: 100,
      hiltScale: 1,
      bladeWidthScale: 1.4,
      dualBlade: null,
    },
  },
  wasp: {
    id: 'wasp',
    name: 'Vespa',
    archetype: 'wasp',
    selectable: true,
    moves: movesByCharacter.wasp,
    aiProfile: 'wasp',
    info: {
      style: 'Velocidade · sequências',
      trait: 'Sequência de cinco golpes rápidos',
      ability: 'Zumbido: avanço que atravessa o oponente',
    },
    sound: {
      humFrequency: 96,
    },
    appearance: {
      cloakColor: '#5c4a33',
      bodyColor: '#2a2219',
      trimColor: '#7a6446',
      saberColor: '#ffd23f',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 0.9,
      torsoLeanDegrees: 16,
      guardAngleDegrees: 40,
      bladeLength: 64,
      hiltScale: 1,
      bladeWidthScale: 0.85,
      dualBlade: { angleOffsetDegrees: 135, lengthScale: 0.85, offsetX: -0.1, offsetY: 0.02 },
    },
  },
  mirror: {
    id: 'mirror',
    name: 'Espelho',
    archetype: 'mirror',
    selectable: true,
    moves: movesByCharacter.mirror,
    aiProfile: 'mirror',
    info: {
      style: 'Defensivo · parry',
      trait: 'Janelas de parry maiores',
      ability: 'Postura de Espera: apara e responde com a riposta',
    },
    sound: {
      humFrequency: 84,
    },
    appearance: {
      cloakColor: '#b9bcc7',
      bodyColor: '#3a3d47',
      trimColor: '#e3e6ee',
      saberColor: '#e8eeff',
      hoodUp: true,
      longCape: true,
      masked: true,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 0,
      guardAngleDegrees: -90,
      bladeLength: 96,
      hiltScale: 1,
      bladeWidthScale: 1,
      dualBlade: null,
    },
  },
  haste: {
    id: 'haste',
    name: 'Haste',
    archetype: 'haste',
    selectable: true,
    moves: movesByCharacter.haste,
    aiProfile: 'haste',
    info: {
      style: 'Alcance · controle de distância',
      trait: 'A ponta da lâmina dá mais dano; de perto, menos',
      ability: 'Varredura: golpe de alcance enorme e lento',
    },
    sound: {
      humFrequency: 68,
    },
    appearance: {
      cloakColor: '#3b3348',
      bodyColor: '#1c1924',
      trimColor: '#564a68',
      saberColor: '#a46bff',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 0.95,
      torsoLeanDegrees: 2,
      guardAngleDegrees: -25,
      bladeLength: 104,
      hiltScale: 3.4,
      bladeWidthScale: 0.9,
      dualBlade: null,
    },
  },
  ember: {
    id: 'ember',
    name: 'Brasa',
    archetype: 'ember',
    selectable: true,
    moves: movesByCharacter.ember,
    aiProfile: 'ember',
    info: {
      style: 'Contra-ataque · leitura',
      trait: 'Mais dano em quem está aberto',
      ability: 'Brasa Viva: postura que responde com um corte forte',
    },
    sound: {
      humFrequency: 80,
    },
    appearance: {
      cloakColor: '#5a2c1e',
      bodyColor: '#24140f',
      trimColor: '#7a3e2a',
      saberColor: '#ff7a2a',
      hoodUp: true,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 12,
      guardAngleDegrees: 115,
      bladeLength: 86,
      hiltScale: 1,
      bladeWidthScale: 1,
      dualBlade: null,
    },
  },
  forge: {
    id: 'forge',
    name: 'Forja',
    archetype: 'forge',
    selectable: true,
    moves: movesByCharacter.forge,
    aiProfile: 'forge',
    info: {
      style: 'Pesada · carga',
      trait: 'Empurra mais longe a cada golpe',
      ability: 'Forja: segure para carregar; o nível 3 quebra a guarda',
    },
    sound: {
      humFrequency: 58,
    },
    appearance: {
      cloakColor: '#4a3a30',
      bodyColor: '#211a15',
      trimColor: '#6b5444',
      saberColor: '#ff4038',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 1.3,
      torsoLeanDegrees: 6,
      guardAngleDegrees: -40,
      bladeLength: 96,
      hiltScale: 1.3,
      bladeWidthScale: 1.7,
      dualBlade: null,
    },
  },
  shadowAwakened: {
    id: 'shadowAwakened',
    name: 'Sombra Desperta',
    archetype: 'shadowAwakened',
    selectable: false,
    moves: movesByCharacter.shadow,
    aiProfile: 'shadow',
    info: {
      style: 'Chefe',
      trait: 'Golpe que acerta devolve stamina',
      ability: 'Ímpeto: avanço com armadura contra um golpe',
    },
    sound: {
      humFrequency: 55,
    },
    appearance: {
      cloakColor: '#14141c',
      bodyColor: '#0a0a0f',
      trimColor: '#3a1030',
      saberColor: '#ff3f9e',
      hoodUp: true,
      longCape: true,
      masked: false,
      pauldrons: true,
      shoulderScale: 1.2,
      torsoLeanDegrees: 12,
      guardAngleDegrees: 25,
      bladeLength: 98,
      hiltScale: 1,
      bladeWidthScale: 1.25,
      dualBlade: null,
    },
  },
};
