import { movesByCharacter } from '../config/movesConfig.js';

export const characters = {
  guardian: {
    id: 'guardian',
    name: 'Guardião',
    archetype: 'guardian',
    moves: movesByCharacter.guardian,
    aiProfile: 'balanced',
    info: {
      style: 'Técnico · fundamentos',
      trait: 'Bloqueio custa menos stamina',
      ability: 'Contraguarda: postura curta que responde com a riposta',
    },
    sound: {
      humFrequency: 74,
    },
    appearance: {
      cloakColor: '#6b5a48',
      bodyColor: '#2e2925',
      trimColor: '#8c7860',
      saberColor: '#7fe4ff',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 3,
      guardAngleDegrees: -60,
      bladeLength: 92,
      bladeWidthScale: 1,
      dualBlade: null,
    },
  },
  shadow: {
    id: 'shadow',
    name: 'Sombra',
    archetype: 'shadow',
    moves: movesByCharacter.shadow,
    aiProfile: 'aggressive',
    info: {
      style: 'Agressiva · pressão',
      trait: 'Golpe que acerta devolve stamina',
      ability: 'Ímpeto: avanço com armadura contra um golpe',
    },
    sound: {
      humFrequency: 62,
    },
    appearance: {
      cloakColor: '#1f2029',
      bodyColor: '#121319',
      trimColor: '#2c2e3a',
      saberColor: '#ff3f9e',
      hoodUp: true,
      longCape: true,
      masked: false,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 10,
      guardAngleDegrees: 25,
      bladeLength: 92,
      bladeWidthScale: 1,
      dualBlade: null,
    },
  },
  bastion: {
    id: 'bastion',
    name: 'Bastião',
    archetype: 'bastion',
    moves: movesByCharacter.bastion,
    aiProfile: 'defensive',
    info: {
      style: 'Tanque · peso',
      trait: 'Anda bloqueando e não é empurrado',
      ability: 'Marreta: golpe lento com armadura contra dois golpes',
    },
    sound: {
      humFrequency: 52,
    },
    appearance: {
      cloakColor: '#3d4636',
      bodyColor: '#1f231c',
      trimColor: '#5a6650',
      saberColor: '#9dff3f',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: true,
      shoulderScale: 1.45,
      torsoLeanDegrees: 2,
      guardAngleDegrees: -15,
      bladeLength: 100,
      bladeWidthScale: 1.4,
      dualBlade: null,
    },
  },
  wasp: {
    id: 'wasp',
    name: 'Vespa',
    archetype: 'wasp',
    moves: movesByCharacter.wasp,
    aiProfile: 'aggressive',
    info: {
      style: 'Velocidade · sequências',
      trait: 'Sequência de cinco golpes rápidos',
      ability: 'Zumbido: avanço que atravessa o oponente',
    },
    sound: {
      humFrequency: 96,
    },
    appearance: {
      cloakColor: '#5c4a33',
      bodyColor: '#2a2219',
      trimColor: '#7a6446',
      saberColor: '#ffd23f',
      hoodUp: false,
      longCape: false,
      masked: false,
      pauldrons: false,
      shoulderScale: 0.9,
      torsoLeanDegrees: 16,
      guardAngleDegrees: 40,
      bladeLength: 64,
      bladeWidthScale: 0.85,
      dualBlade: { angleOffsetDegrees: 135, lengthScale: 0.85, offsetX: -0.1, offsetY: 0.02 },
    },
  },
  mirror: {
    id: 'mirror',
    name: 'Espelho',
    archetype: 'mirror',
    moves: movesByCharacter.mirror,
    aiProfile: 'defensive',
    info: {
      style: 'Defensivo · parry',
      trait: 'Janelas de parry maiores',
      ability: 'Postura de Espera: apara e responde com a riposta',
    },
    sound: {
      humFrequency: 84,
    },
    appearance: {
      cloakColor: '#b9bcc7',
      bodyColor: '#3a3d47',
      trimColor: '#e3e6ee',
      saberColor: '#e8eeff',
      hoodUp: true,
      longCape: true,
      masked: true,
      pauldrons: false,
      shoulderScale: 1,
      torsoLeanDegrees: 0,
      guardAngleDegrees: -90,
      bladeLength: 96,
      bladeWidthScale: 1,
      dualBlade: null,
    },
  },
};
