export const Difficulty = Object.freeze({
  EASY: 'easy',
  NORMAL: 'normal',
  HARD: 'hard',
});

export const AiProfile = Object.freeze({
  AGGRESSIVE: 'aggressive',
  DEFENSIVE: 'defensive',
  BALANCED: 'balanced',
});

export const aiConfig = {
  defaultDifficulty: Difficulty.NORMAL,
  difficultyOrder: [Difficulty.EASY, Difficulty.NORMAL, Difficulty.HARD],
  bossDifficulty: 'boss',
  difficulties: {
    [Difficulty.EASY]: {
      reactionTime: 0.45,
      evadeChance: 0.005,
      powerMultiplier: 0.5,
      powerAware: false,
      jumpChance: 0.005,
      airJumpChance: 0.5,
      airDashChance: 0.1,
      cornerJumpChance: 0.05,
      evadeTimingJitter: 0.06,
      defenseMultiplier: 0.35,
      mistakeChance: 0.3,
      attackCooldown: 1,
      parryChance: 0,
      perfectParryChance: 0,
      shoveMultiplier: 0.3,
      attackTell: 0.25,
      smartPunish: false,
      whiffBaitChance: 0,
      adaptation: 0,
      chainChance: 0.2,
      specialMultiplier: 0.3,
      blockPunishChance: 0.15,
      recoveryGuardChance: 0.1,
    },
    [Difficulty.NORMAL]: {
      reactionTime: 0.28,
      evadeChance: 0.015,
      powerMultiplier: 1,
      powerAware: true,
      jumpChance: 0.008,
      airJumpChance: 0.7,
      airDashChance: 0.3,
      cornerJumpChance: 0.12,
      evadeTimingJitter: 0.04,
      defenseMultiplier: 0.7,
      mistakeChance: 0.12,
      attackCooldown: 0.65,
      parryChance: 0.38,
      perfectParryChance: 0.1,
      shoveMultiplier: 0.7,
      attackTell: 0.08,
      smartPunish: false,
      whiffBaitChance: 0.1,
      adaptation: 0,
      chainChance: 0.6,
      specialMultiplier: 0.7,
      blockPunishChance: 0.55,
      recoveryGuardChance: 0.5,
    },
    [Difficulty.HARD]: {
      reactionTime: 0.15,
      evadeChance: 0.04,
      powerMultiplier: 1.2,
      powerAware: true,
      jumpChance: 0.01,
      airJumpChance: 0.85,
      airDashChance: 0.5,
      cornerJumpChance: 0.2,
      evadeTimingJitter: 0.025,
      defenseMultiplier: 1,
      mistakeChance: 0.04,
      attackCooldown: 0.4,
      parryChance: 0.5,
      perfectParryChance: 0.25,
      shoveMultiplier: 1,
      attackTell: 0,
      smartPunish: true,
      whiffBaitChance: 0.25,
      adaptation: 1,
      chainChance: 0.8,
      specialMultiplier: 0.85,
      blockPunishChance: 0.85,
      recoveryGuardChance: 0.75,
    },
    boss: {
      reactionTime: 0.15,
      evadeChance: 0.04,
      powerMultiplier: 1.2,
      powerAware: true,
      jumpChance: 0.01,
      airJumpChance: 0.85,
      airDashChance: 0.5,
      cornerJumpChance: 0.2,
      evadeTimingJitter: 0.025,
      defenseMultiplier: 1,
      mistakeChance: 0.02,
      attackCooldown: 0.25,
      parryChance: 0.65,
      perfectParryChance: 0.3,
      shoveMultiplier: 1,
      attackTell: 0,
      smartPunish: true,
      whiffBaitChance: 0.25,
      adaptation: 1,
      chainChance: 1,
      specialMultiplier: 1,
      blockPunishChance: 0.9,
      recoveryGuardChance: 0.8,
    },
  },
  profiles: {
    [AiProfile.AGGRESSIVE]: {
      attackChance: 0.7,
      heavyChance: 0.35,
      blockChance: 0.42,
      dodgeChance: 0.1,
      counterChance: 0.8,
      guardChance: 0.18,
      shoveChance: 0.45,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      specialChance: 0.35,
      preferredGap: 40,
      retreatStaminaRatio: 0.2,
    },
    [AiProfile.DEFENSIVE]: {
      attackChance: 0.35,
      heavyChance: 0.2,
      blockChance: 0.7,
      dodgeChance: 0.2,
      counterChance: 0.9,
      guardChance: 0.5,
      shoveChance: 0.2,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      specialChance: 0.4,
      preferredGap: 90,
      retreatStaminaRatio: 0.4,
    },
    [AiProfile.BALANCED]: {
      attackChance: 0.68,
      heavyChance: 0.25,
      blockChance: 0.5,
      dodgeChance: 0.15,
      counterChance: 0.75,
      guardChance: 0.3,
      shoveChance: 0.3,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      specialChance: 0.3,
      preferredGap: 60,
      retreatStaminaRatio: 0.3,
    },
    guardian: {
      attackChance: 0.65,
      heavyChance: 0.25,
      blockChance: 0.55,
      dodgeChance: 0.15,
      counterChance: 0.8,
      guardChance: 0.35,
      shoveChance: 0.3,
      specialChance: 0.3,
      preferredGap: 60,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 0.6,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
    },
    shadow: {
      attackChance: 0.72,
      heavyChance: 0.35,
      blockChance: 0.42,
      dodgeChance: 0.1,
      counterChance: 0.85,
      guardChance: 0.18,
      shoveChance: 0.45,
      specialChance: 0.3,
      preferredGap: 40,
      retreatStaminaRatio: 0.2,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 0.6,
      priorities: ['defend', 'counter', 'special', 'power', 'shove', 'attack', 'recover', 'guard', 'position'],
    },
    bastion: {
      attackChance: 0.5,
      heavyChance: 0.4,
      blockChance: 0.65,
      dodgeChance: 0.05,
      counterChance: 0.85,
      guardChance: 0.55,
      shoveChance: 0.35,
      specialChance: 0.3,
      preferredGap: 50,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 0.3,
      priorities: ['defend', 'counter', 'special', 'power', 'attack', 'guard', 'shove', 'recover', 'position'],
    },
    wasp: {
      attackChance: 0.8,
      heavyChance: 0.15,
      blockChance: 0.35,
      dodgeChance: 0.3,
      evadeWeight: 1.2,
      counterChance: 0.9,
      guardChance: 0.15,
      shoveChance: 0.35,
      specialChance: 0.5,
      preferredGap: 30,
      retreatStaminaRatio: 0.25,
      closeGapRatio: 0.4,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 1,
      priorities: ['defend', 'counter', 'power', 'attack', 'shove', 'recover', 'guard', 'position'],
    },
    mirror: {
      attackChance: 0.55,
      heavyChance: 0.2,
      blockChance: 0.8,
      dodgeChance: 0.15,
      counterChance: 1,
      guardChance: 0.45,
      shoveChance: 0.25,
      specialChance: 0.15,
      preferredGap: 70,
      retreatStaminaRatio: 0.4,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 0.6,
      priorities: ['defend', 'counter', 'guard', 'special', 'power', 'recover', 'shove', 'attack', 'position'],
    },
    haste: {
      attackChance: 0.65,
      heavyChance: 0.3,
      blockChance: 0.65,
      dodgeChance: 0.2,
      counterChance: 0.8,
      guardChance: 0.35,
      shoveChance: 0.35,
      specialChance: 0.3,
      preferredGap: 125,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.6,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 0.3,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'position', 'guard'],
    },
    ember: {
      attackChance: 0.5,
      heavyChance: 0.25,
      blockChance: 0.55,
      dodgeChance: 0.15,
      counterChance: 1,
      guardChance: 0.4,
      shoveChance: 0.3,
      specialChance: 0.18,
      preferredGap: 60,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 0.6,
      priorities: ['defend', 'counter', 'special', 'power', 'recover', 'attack', 'guard', 'shove', 'position'],
    },
    forge: {
      attackChance: 0.6,
      heavyChance: 0.45,
      blockChance: 0.5,
      dodgeChance: 0.1,
      counterChance: 0.85,
      guardChance: 0.3,
      shoveChance: 0.35,
      specialChance: 0.35,
      preferredGap: 55,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.5,
      chargeHold: 0.6,
      feintChance: 0,
      aerialWeight: 0.3,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
    },
    heron: {
      attackChance: 0.7,
      heavyChance: 0.2,
      blockChance: 0.4,
      dodgeChance: 0.3,
      evadeWeight: 1.2,
      counterChance: 0.85,
      guardChance: 0.2,
      shoveChance: 0.25,
      specialChance: 0.25,
      preferredGap: 50,
      retreatStaminaRatio: 0.25,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 1,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
    },
    sovereign: {
      attackChance: 0.6,
      heavyChance: 0.3,
      blockChance: 0.7,
      dodgeChance: 0.2,
      counterChance: 0.9,
      guardChance: 0.4,
      shoveChance: 0.3,
      specialChance: 0.3,
      powerChance: 0.6,
      preferredGap: 140,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.6,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 0.3,
      priorities: ['defend', 'counter', 'power', 'shove', 'recover', 'special', 'attack', 'position', 'guard'],
    },
    elder: {
      attackChance: 0.6,
      heavyChance: 0.2,
      blockChance: 0.75,
      dodgeChance: 0.25,
      evadeWeight: 1.4,
      counterChance: 1,
      guardChance: 0.4,
      shoveChance: 0.3,
      specialChance: 0.3,
      powerChance: 0.5,
      preferredGap: 60,
      retreatStaminaRatio: 0.25,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0,
      aerialWeight: 1,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
    },
    foretold: {
      attackChance: 0.65,
      heavyChance: 0.25,
      blockChance: 0.6,
      dodgeChance: 0.2,
      counterChance: 1,
      guardChance: 0.35,
      shoveChance: 0.3,
      specialChance: 0.3,
      powerChance: 0.45,
      preferredGap: 60,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0.25,
      aerialWeight: 1,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
    },
    echo: {
      attackChance: 0.62,
      heavyChance: 0.4,
      blockChance: 0.5,
      dodgeChance: 0.2,
      counterChance: 0.85,
      guardChance: 0.3,
      shoveChance: 0.3,
      specialChance: 0.3,
      preferredGap: 60,
      retreatStaminaRatio: 0.3,
      closeGapRatio: 0.5,
      chargeHold: 0.4,
      feintChance: 0.2,
      aerialWeight: 1,
      priorities: ['defend', 'counter', 'shove', 'recover', 'special', 'power', 'attack', 'guard', 'position'],
    },
  },
  perception: {
    reactionJitter: 0.4,
    evadeWeight: 1,
    airJumpFallSpeed: 0,
    airDashCrossGap: 70,
    airDashClearance: 0.7,
    cornerMargin: 110,
    reachMargin: 10,
    threatMargin: 20,
    safeGapExtra: 80,
    closeGapRatio: 0.5,
    blockHoldTime: 0.35,
    punishMargin: 0.08,
    leapGap: 120,
    powerChance: 0.35,
    powerChannelReserve: 0.4,
    lightningHold: [0.4, 1],
    barrierPreference: 0.6,
    barrierVsSaberChance: 0.15,
    powerUse: {
      push: { minGap: 0, maxGap: 100 },
      pull: { minGap: 250, maxGap: Infinity },
      lightning: { minGap: 110, maxGap: Infinity },
    },
    feintAt: 0.45,
    habits: {
      attackDecay: 0.85,
      blockDecayPerSecond: 0.25,
      thresholds: { heavy: 0.4, block: 0.35, light: 0.75 },
      bonuses: { heavy: 0.25, block: 0.3, light: 0.2 },
    },
  },
};
