export const Action = Object.freeze({
  MOVE_LEFT: 'moveLeft',
  MOVE_RIGHT: 'moveRight',
  JUMP: 'jump',
  LIGHT_ATTACK: 'lightAttack',
  HEAVY_ATTACK: 'heavyAttack',
  BLOCK: 'block',
  DODGE: 'dodge',
  CONFIRM: 'confirm',
  BACK: 'back',
  MENU_UP: 'menuUp',
  MENU_DOWN: 'menuDown',
  PAUSE: 'pause',
  TOGGLE_DEBUG: 'toggleDebug',
  CYCLE_DUMMY: 'cycleDummy',
});

export const keyBindings = {
  [Action.MOVE_LEFT]: ['KeyA', 'ArrowLeft'],
  [Action.MOVE_RIGHT]: ['KeyD', 'ArrowRight'],
  [Action.JUMP]: ['KeyW', 'ArrowUp', 'Space'],
  [Action.LIGHT_ATTACK]: ['KeyJ'],
  [Action.HEAVY_ATTACK]: ['KeyK'],
  [Action.BLOCK]: ['KeyL'],
  [Action.DODGE]: ['ShiftLeft', 'ShiftRight'],
  [Action.CONFIRM]: ['Enter', 'NumpadEnter'],
  [Action.BACK]: ['Escape', 'Backspace'],
  [Action.MENU_UP]: ['ArrowUp', 'KeyW'],
  [Action.MENU_DOWN]: ['ArrowDown', 'KeyS'],
  [Action.PAUSE]: ['Escape', 'KeyP'],
  [Action.TOGGLE_DEBUG]: ['F3'],
  [Action.CYCLE_DUMMY]: ['F4'],
};
