export const proportions = {
  legLength: 0.45,
  torsoLength: 0.33,
  headRadius: 0.075,
  neckGap: 0.025,
  stanceWidth: 0.11,
  kneeBend: 0.05,
  legWidth: 0.06,
  armWidth: 0.055,
  handForward: 0.13,
  handHeight: 0.08,
  handRadius: 0.03,
  shoulderWidth: 0.075,
  tunicLength: 0.2,
  tunicFlare: 0.1,
  hiltLength: 0.09,
};

export const animation = {
  breathPeriod: 3.2,
  breathAmplitude: 1.5,
  saberSwayDegrees: 2.5,
  strideLength: 34,
  stepLength: 0.09,
  stepLift: 0.05,
  walkBob: 2.5,
  walkBreathDamping: 0.5,
  clothDrag: 0.03,
  maxClothSway: 10,
  walkBlendRate: 10,
  airBlendRate: 14,
  airLegTuck: 0.12,
  airFootPull: 0.4,
};

export const combatPoses = {
  attacks: {
    spin: {
      windupDegrees: 150,
      strikeDegrees: -200,
      windupLean: 5,
      strikeLean: -4,
      windupLift: 0.06,
      strikeReach: 0.04,
    },
    saberThrow: {
      windupDegrees: -150,
      strikeDegrees: 10,
      windupLean: -8,
      strikeLean: 14,
      windupLift: 0.12,
      strikeReach: 0.24,
    },
    dashSlash: {
      windupDegrees: 35,
      strikeDegrees: -80,
      windupLean: 14,
      strikeLean: 20,
      windupLift: 0.02,
      strikeReach: 0.2,
    },
    light: {
      windupDegrees: -115,
      strikeDegrees: 30,
      windupLean: -3,
      strikeLean: 6,
      windupLift: 0.08,
      strikeReach: 0.08,
    },
    heavy: {
      windupDegrees: -160,
      strikeDegrees: 55,
      windupLean: -6,
      strikeLean: 12,
      windupLift: 0.14,
      strikeReach: 0.12,
    },
    riposte: {
      windupDegrees: -70,
      strikeDegrees: 40,
      windupLean: -2,
      strikeLean: 14,
      windupLift: 0.04,
      strikeReach: 0.15,
    },
    lightReverse: {
      windupDegrees: 60,
      strikeDegrees: -70,
      windupLean: 4,
      strikeLean: 8,
      windupLift: 0.02,
      strikeReach: 0.1,
    },
    hammer: {
      windupDegrees: -175,
      strikeDegrees: 70,
      windupLean: -10,
      strikeLean: 16,
      windupLift: 0.18,
      strikeReach: 0.1,
    },
    waitingStance: {
      windupDegrees: -90,
      strikeDegrees: -90,
      windupLean: 0,
      strikeLean: 0,
      windupLift: 0.16,
      strikeReach: 0,
    },
    thrust: {
      windupDegrees: -10,
      strikeDegrees: 0,
      windupLean: -6,
      strikeLean: 14,
      windupLift: 0.02,
      strikeReach: 0.22,
    },
    sweep: {
      windupDegrees: -130,
      strikeDegrees: 10,
      windupLean: -8,
      strikeLean: 18,
      windupLift: 0.04,
      strikeReach: 0.3,
    },
    stance: {
      windupDegrees: -20,
      strikeDegrees: -20,
      windupLean: -5,
      strikeLean: -5,
      windupLift: 0.12,
      strikeReach: 0.04,
    },
    impetus: {
      windupDegrees: -150,
      strikeDegrees: 40,
      windupLean: 8,
      strikeLean: 18,
      windupLift: 0.06,
      strikeReach: 0.16,
    },
    shove: {
      windupDegrees: -40,
      strikeDegrees: -75,
      windupLean: -6,
      strikeLean: 16,
      windupLift: 0.02,
      strikeReach: 0.12,
    },
  },
  block: {
    bladeDegrees: -95,
    reach: 0.05,
    lift: 0.06,
    crouch: 6,
  },
  evade: { lean: -22, crouch: 8, releaseTime: 0.1 },
  powers: {
    cast: { bladeDegrees: 115, lean: 12, crouch: 4, reach: 0.06, lift: 0, tremble: 0, trembleSpeed: 0 },
    channel: { bladeDegrees: 125, lean: 8, crouch: 8, reach: 0.04, lift: 0, tremble: 2.5, trembleSpeed: 9 },
    barrier: { bladeDegrees: -100, lean: -2, crouch: 12, reach: 0, lift: 0.04, tremble: 0, trembleSpeed: 0 },
  },
  dodge: {
    lean: 14,
    crouch: 14,
  },
  hit: {
    lean: -14,
    bladeDropDegrees: 35,
  },
  staggered: {
    lean: -12,
    crouch: 4,
    bladeDegrees: -150,
  },
  stunned: {
    lean: 18,
    crouch: 10,
    bladeDegrees: 70,
    swayDegrees: 6,
    swaySpeed: 3,
  },
  dead: {
    fallDuration: 0.45,
    fallDegrees: 88,
    lift: 0.2,
  },
};

export const groundShadow = {
  radiusXRatio: 0.8,
  radiusY: 6,
  fadeHeight: 300,
  minScale: 0.4,
};

export const saberStyle = {
  hiltWidth: 4,
  outerGlowWidth: 16,
  outerGlowAlpha: 0.15,
  glowWidth: 7,
  glowAlpha: 0.55,
  coreWidth: 3,
  floorLightAlpha: 0.12,
  floorLightRadiusX: 70,
  floorLightRadiusY: 10,
  bodyLightRadius: 120,
  bodyLightAlpha: 0.14,
  flareWidth: 22,
  flareAlpha: 0.5,
  staggerFlickerSpeed: 22,
  staggerFlickerMin: 0.35,
};

export const afterimage = {
  evade: { interval: 0.05, duration: 0.12, alpha: 0.18 },
  count: 3,
  interval: 0.05,
  duration: 0.25,
  alpha: 0.3,
};

export const saberTrail = {
  maxSamples: 8,
  duration: 0.12,
  alpha: 0.35,
};
