export const fighterArchetypes = {
  guardian: {
    maxHealth: 100,
    maxStamina: 100,
    body: {
      width: 46,
      height: 150,
    },
    movement: {
      walkSpeed: 260,
      backwardSpeedMultiplier: 0.75,
      groundAcceleration: 2200,
      groundDeceleration: 2800,
      airAcceleration: 900,
      jumpVelocity: 820,
    },
    stamina: {
      regenPerSecond: 25,
      regenDelay: 0.6,
      blockingRegenMultiplier: 0.4,
    },
    attacks: {
      light: {
        damage: 10,
        staminaCost: 8,
        startup: 0.1,
        active: 0.1,
        recovery: 0.2,
        lunge: 120,
        knockback: 160,
        hitstun: 0.28,
        blockstun: 0.14,
        blockStaminaCost: 8,
        blockPushback: 120,
        hitbox: { reach: 100, top: 0.8, bottom: 0.35 },
      },
      heavy: {
        damage: 24,
        staminaCost: 24,
        startup: 0.32,
        active: 0.12,
        recovery: 0.42,
        lunge: 220,
        knockback: 360,
        hitstun: 0.5,
        blockstun: 0.24,
        blockStaminaCost: 30,
        blockPushback: 220,
        hitbox: { reach: 115, top: 0.9, bottom: 0.25 },
      },
      riposte: {
        damage: 16,
        staminaCost: 0,
        startup: 0.06,
        active: 0.1,
        recovery: 0.3,
        lunge: 180,
        knockback: 320,
        hitstun: 0.45,
        blockstun: 0.2,
        blockStaminaCost: 16,
        blockPushback: 200,
        hitbox: { reach: 110, top: 0.85, bottom: 0.3 },
      },
      shove: {
        damage: 0,
        staminaCost: 10,
        staminaDamage: 20,
        startup: 0.2,
        active: 0.08,
        recovery: 0.3,
        lunge: 140,
        knockback: 260,
        hitstun: 0.35,
        blockstun: 0,
        blockStaminaCost: 0,
        blockPushback: 0,
        hitbox: { reach: 50, top: 0.8, bottom: 0.3 },
      },
    },
    parry: {
      perfectWindow: 0.08,
      window: 0.2,
      lockout: 0.4,
      stagger: 0.3,
      perfectStagger: 0.5,
      perfectStaminaGain: 15,
      perfectStaminaDamageMultiplier: 2,
      attackerRecoil: 60,
    },
    dodge: {
      staminaCost: 20,
      speed: 560,
      duration: 0.28,
      invulnerableTime: 0.18,
    },
    blockStaminaScale: 0.75,
    blockPushbackScale: 1,
    blockWalkSpeed: 0,
    staminaOnHit: 0,
    punishDamageScale: 1,
    knockbackScale: 1,
    guardBreakStun: 0.9,
  },
  shadow: {
    maxHealth: 100,
    maxStamina: 100,
    body: {
      width: 48,
      height: 154,
    },
    movement: {
      walkSpeed: 250,
      backwardSpeedMultiplier: 0.7,
      groundAcceleration: 2000,
      groundDeceleration: 2600,
      airAcceleration: 800,
      jumpVelocity: 800,
    },
    stamina: {
      regenPerSecond: 25,
      regenDelay: 0.6,
      blockingRegenMultiplier: 0.4,
    },
    attacks: {
      light: {
        damage: 10,
        staminaCost: 8,
        startup: 0.1,
        active: 0.1,
        recovery: 0.22,
        lunge: 110,
        knockback: 170,
        hitstun: 0.28,
        blockstun: 0.15,
        blockStaminaCost: 8,
        blockPushback: 130,
        hitbox: { reach: 100, top: 0.75, bottom: 0.3 },
      },
      heavy: {
        damage: 24,
        staminaCost: 25,
        startup: 0.34,
        active: 0.12,
        recovery: 0.44,
        lunge: 240,
        knockback: 400,
        hitstun: 0.55,
        blockstun: 0.28,
        blockStaminaCost: 32,
        blockPushback: 240,
        hitbox: { reach: 120, top: 0.85, bottom: 0.2 },
      },
      riposte: {
        damage: 17,
        staminaCost: 0,
        startup: 0.06,
        active: 0.1,
        recovery: 0.3,
        lunge: 180,
        knockback: 340,
        hitstun: 0.45,
        blockstun: 0.2,
        blockStaminaCost: 16,
        blockPushback: 200,
        hitbox: { reach: 110, top: 0.85, bottom: 0.3 },
      },
      shove: {
        damage: 0,
        staminaCost: 10,
        staminaDamage: 20,
        startup: 0.2,
        active: 0.08,
        recovery: 0.3,
        lunge: 140,
        knockback: 260,
        hitstun: 0.35,
        blockstun: 0,
        blockStaminaCost: 0,
        blockPushback: 0,
        hitbox: { reach: 50, top: 0.8, bottom: 0.3 },
      },
    },
    parry: {
      perfectWindow: 0.08,
      window: 0.2,
      lockout: 0.4,
      stagger: 0.3,
      perfectStagger: 0.5,
      perfectStaminaGain: 15,
      perfectStaminaDamageMultiplier: 2,
      attackerRecoil: 60,
    },
    dodge: {
      staminaCost: 22,
      speed: 520,
      duration: 0.3,
      invulnerableTime: 0.18,
    },
    blockStaminaScale: 1,
    blockPushbackScale: 1,
    blockWalkSpeed: 0,
    staminaOnHit: 4,
    punishDamageScale: 1,
    knockbackScale: 1,
    guardBreakStun: 1,
  },
  bastion: {
    maxHealth: 118,
    maxStamina: 110,
    body: {
      width: 58,
      height: 160,
    },
    movement: {
      walkSpeed: 200,
      backwardSpeedMultiplier: 0.65,
      groundAcceleration: 1600,
      groundDeceleration: 2200,
      airAcceleration: 600,
      jumpVelocity: 700,
    },
    stamina: {
      regenPerSecond: 24,
      regenDelay: 0.6,
      blockingRegenMultiplier: 0.4,
    },
    attacks: {
      light: {
        damage: 11,
        staminaCost: 9,
        startup: 0.12,
        active: 0.1,
        recovery: 0.26,
        lunge: 90,
        knockback: 200,
        hitstun: 0.3,
        blockstun: 0.16,
        blockStaminaCost: 10,
        blockPushback: 140,
        hitbox: { reach: 105, top: 0.8, bottom: 0.35 },
      },
      heavy: {
        damage: 28,
        staminaCost: 26,
        startup: 0.4,
        active: 0.14,
        recovery: 0.5,
        lunge: 180,
        knockback: 440,
        hitstun: 0.55,
        blockstun: 0.3,
        blockStaminaCost: 36,
        blockPushback: 260,
        hitbox: { reach: 120, top: 0.9, bottom: 0.25 },
      },
      riposte: {
        damage: 18,
        staminaCost: 0,
        startup: 0.07,
        active: 0.1,
        recovery: 0.32,
        lunge: 160,
        knockback: 340,
        hitstun: 0.45,
        blockstun: 0.2,
        blockStaminaCost: 18,
        blockPushback: 200,
        hitbox: { reach: 110, top: 0.85, bottom: 0.3 },
      },
      shove: {
        damage: 0,
        staminaCost: 10,
        staminaDamage: 26,
        startup: 0.2,
        active: 0.08,
        recovery: 0.3,
        lunge: 140,
        knockback: 320,
        hitstun: 0.35,
        blockstun: 0,
        blockStaminaCost: 0,
        blockPushback: 0,
        hitbox: { reach: 50, top: 0.8, bottom: 0.3 },
      },
    },
    parry: {
      perfectWindow: 0.07,
      window: 0.18,
      lockout: 0.4,
      stagger: 0.3,
      perfectStagger: 0.5,
      perfectStaminaGain: 15,
      perfectStaminaDamageMultiplier: 2,
      attackerRecoil: 60,
    },
    dodge: {
      staminaCost: 26,
      speed: 440,
      duration: 0.3,
      invulnerableTime: 0.16,
    },
    blockStaminaScale: 1,
    blockPushbackScale: 0,
    blockWalkSpeed: 110,
    staminaOnHit: 0,
    punishDamageScale: 1,
    knockbackScale: 1.1,
    guardBreakStun: 0.8,
  },
  wasp: {
    maxHealth: 98,
    maxStamina: 100,
    body: {
      width: 42,
      height: 138,
    },
    movement: {
      walkSpeed: 310,
      backwardSpeedMultiplier: 0.85,
      groundAcceleration: 2800,
      groundDeceleration: 3200,
      airAcceleration: 1100,
      jumpVelocity: 880,
    },
    stamina: {
      regenPerSecond: 30,
      regenDelay: 0.6,
      blockingRegenMultiplier: 0.4,
    },
    attacks: {
      light: {
        damage: 7,
        staminaCost: 6,
        startup: 0.08,
        active: 0.08,
        recovery: 0.18,
        lunge: 130,
        knockback: 110,
        hitstun: 0.26,
        blockstun: 0.12,
        blockStaminaCost: 10,
        blockPushback: 90,
        hitbox: { reach: 86, top: 0.8, bottom: 0.35 },
      },
      heavy: {
        damage: 18,
        staminaCost: 22,
        startup: 0.3,
        active: 0.1,
        recovery: 0.4,
        lunge: 240,
        knockback: 300,
        hitstun: 0.45,
        blockstun: 0.22,
        blockStaminaCost: 26,
        blockPushback: 200,
        hitbox: { reach: 95, top: 0.85, bottom: 0.25 },
      },
      riposte: {
        damage: 14,
        staminaCost: 0,
        startup: 0.05,
        active: 0.08,
        recovery: 0.26,
        lunge: 200,
        knockback: 280,
        hitstun: 0.42,
        blockstun: 0.18,
        blockStaminaCost: 14,
        blockPushback: 180,
        hitbox: { reach: 95, top: 0.85, bottom: 0.3 },
      },
      shove: {
        damage: 0,
        staminaCost: 10,
        staminaDamage: 18,
        startup: 0.2,
        active: 0.08,
        recovery: 0.3,
        lunge: 140,
        knockback: 240,
        hitstun: 0.35,
        blockstun: 0,
        blockStaminaCost: 0,
        blockPushback: 0,
        hitbox: { reach: 50, top: 0.8, bottom: 0.3 },
      },
    },
    parry: {
      perfectWindow: 0.08,
      window: 0.2,
      lockout: 0.4,
      stagger: 0.3,
      perfectStagger: 0.5,
      perfectStaminaGain: 15,
      perfectStaminaDamageMultiplier: 2,
      attackerRecoil: 60,
    },
    dodge: {
      staminaCost: 16,
      speed: 640,
      duration: 0.24,
      invulnerableTime: 0.18,
    },
    blockStaminaScale: 1,
    blockPushbackScale: 1,
    blockWalkSpeed: 0,
    staminaOnHit: 0,
    punishDamageScale: 1,
    knockbackScale: 1,
    guardBreakStun: 1,
  },
  mirror: {
    maxHealth: 100,
    maxStamina: 100,
    body: {
      width: 46,
      height: 156,
    },
    movement: {
      walkSpeed: 240,
      backwardSpeedMultiplier: 0.8,
      groundAcceleration: 2100,
      groundDeceleration: 2700,
      airAcceleration: 850,
      jumpVelocity: 800,
    },
    stamina: {
      regenPerSecond: 26,
      regenDelay: 0.6,
      blockingRegenMultiplier: 0.4,
    },
    attacks: {
      light: {
        damage: 10,
        staminaCost: 8,
        startup: 0.11,
        active: 0.1,
        recovery: 0.24,
        lunge: 110,
        knockback: 160,
        hitstun: 0.28,
        blockstun: 0.14,
        blockStaminaCost: 8,
        blockPushback: 120,
        hitbox: { reach: 100, top: 0.8, bottom: 0.35 },
      },
      heavy: {
        damage: 24,
        staminaCost: 24,
        startup: 0.34,
        active: 0.12,
        recovery: 0.44,
        lunge: 210,
        knockback: 360,
        hitstun: 0.5,
        blockstun: 0.24,
        blockStaminaCost: 30,
        blockPushback: 220,
        hitbox: { reach: 115, top: 0.9, bottom: 0.25 },
      },
      riposte: {
        damage: 20,
        staminaCost: 0,
        startup: 0.06,
        active: 0.1,
        recovery: 0.3,
        lunge: 180,
        knockback: 340,
        hitstun: 0.48,
        blockstun: 0.2,
        blockStaminaCost: 18,
        blockPushback: 200,
        hitbox: { reach: 112, top: 0.85, bottom: 0.3 },
      },
      shove: {
        damage: 0,
        staminaCost: 10,
        staminaDamage: 20,
        startup: 0.2,
        active: 0.08,
        recovery: 0.3,
        lunge: 140,
        knockback: 260,
        hitstun: 0.35,
        blockstun: 0,
        blockStaminaCost: 0,
        blockPushback: 0,
        hitbox: { reach: 50, top: 0.8, bottom: 0.3 },
      },
    },
    parry: {
      perfectWindow: 0.12,
      window: 0.26,
      lockout: 0.35,
      stagger: 0.32,
      perfectStagger: 0.55,
      perfectStaminaGain: 15,
      perfectStaminaDamageMultiplier: 2,
      attackerRecoil: 60,
    },
    dodge: {
      staminaCost: 20,
      speed: 560,
      duration: 0.28,
      invulnerableTime: 0.18,
    },
    blockStaminaScale: 1,
    blockPushbackScale: 1,
    blockWalkSpeed: 0,
    staminaOnHit: 0,
    punishDamageScale: 1,
    knockbackScale: 1,
    guardBreakStun: 0.9,
  },
  shadowAwakened: {
    maxHealth: 150,
    maxStamina: 100,
    body: {
      width: 48,
      height: 154,
    },
    movement: {
      walkSpeed: 250,
      backwardSpeedMultiplier: 0.7,
      groundAcceleration: 2000,
      groundDeceleration: 2600,
      airAcceleration: 800,
      jumpVelocity: 800,
    },
    stamina: {
      regenPerSecond: 30,
      regenDelay: 0.6,
      blockingRegenMultiplier: 0.4,
    },
    attacks: {
      light: {
        damage: 10,
        staminaCost: 8,
        startup: 0.1,
        active: 0.1,
        recovery: 0.22,
        lunge: 110,
        knockback: 170,
        hitstun: 0.28,
        blockstun: 0.15,
        blockStaminaCost: 8,
        blockPushback: 130,
        hitbox: { reach: 100, top: 0.75, bottom: 0.3 },
      },
      heavy: {
        damage: 28,
        staminaCost: 25,
        startup: 0.34,
        active: 0.12,
        recovery: 0.44,
        lunge: 240,
        knockback: 400,
        hitstun: 0.55,
        blockstun: 0.28,
        blockStaminaCost: 32,
        blockPushback: 240,
        hitbox: { reach: 120, top: 0.85, bottom: 0.2 },
      },
      riposte: {
        damage: 17,
        staminaCost: 0,
        startup: 0.06,
        active: 0.1,
        recovery: 0.3,
        lunge: 180,
        knockback: 340,
        hitstun: 0.45,
        blockstun: 0.2,
        blockStaminaCost: 16,
        blockPushback: 200,
        hitbox: { reach: 110, top: 0.85, bottom: 0.3 },
      },
      shove: {
        damage: 0,
        staminaCost: 10,
        staminaDamage: 20,
        startup: 0.2,
        active: 0.08,
        recovery: 0.3,
        lunge: 140,
        knockback: 260,
        hitstun: 0.35,
        blockstun: 0,
        blockStaminaCost: 0,
        blockPushback: 0,
        hitbox: { reach: 50, top: 0.8, bottom: 0.3 },
      },
    },
    parry: {
      perfectWindow: 0.08,
      window: 0.2,
      lockout: 0.4,
      stagger: 0.3,
      perfectStagger: 0.5,
      perfectStaminaGain: 15,
      perfectStaminaDamageMultiplier: 2,
      attackerRecoil: 60,
    },
    dodge: {
      staminaCost: 22,
      speed: 520,
      duration: 0.3,
      invulnerableTime: 0.18,
    },
    blockStaminaScale: 1,
    blockPushbackScale: 1,
    blockWalkSpeed: 0,
    staminaOnHit: 6,
    punishDamageScale: 1,
    knockbackScale: 1,
    guardBreakStun: 1,
  },
};
