export const storyConfig = {
  start: 'trial',
  pointsPerVictory: 2,
  startPoints: 4,
  startAttributes: { health: 4, stamina: 4, blade: 4, defense: 4, agility: 4, flow: 4 },
  ratingCaps: { easy: 8, normal: 7, hard: 6 },
  budgets: { easy: 40, normal: 37, hard: 34 },
  difficulties: ['easy', 'normal', 'hard'],
  rules: { powers: true },
  roundsToWin: 1,
  protagonist: {
    names: ['Kael', 'Iria', 'Tarin', 'Vessa', 'Oren', 'Lyse'],
    maxNameLength: 16,
    alignments: ['light', 'dark'],
    styles: {
      technique: { base: 'guardian' },
      fury: { base: 'shadow' },
      flight: { base: 'heron' },
    },
    saberColors: ['#7fe4ff', '#9dff3f', '#ffd23f', '#e8eeff', '#a46bff', '#ff7a2a', '#5fffc0', '#ffa6e0', '#ff3f9e', '#ff4038'],
    appearance: {
      cloakColor: '#3e4a5e',
      bodyColor: '#1d222b',
      trimColor: '#7f90aa',
      hoodUp: false,
      longCape: true,
      masked: false,
      scarf: true,
    },
  },
  encounters: [
    { id: 'trial', opponent: 'guardian', arena: 'refinery', aiOffset: -1, next: 'forest' },
    { id: 'forest', opponent: 'echo', arena: 'forest', aiOffset: -1, next: 'rooftop' },
    { id: 'rooftop', opponent: 'wasp', arena: 'rooftop', aiOffset: 0, reward: { powers: true }, next: 'mine' },
    { id: 'mine', opponent: 'ember', arena: 'crystalMine', aiOffset: 0, next: 'sanctuary' },
    { id: 'sanctuary', opponent: 'bastion', arena: 'sanctuary', aiOffset: 0, next: 'shadowDuel' },
    { id: 'shadowDuel', opponent: 'shadow', arena: 'refinery', aiOffset: 0, next: 'awakened' },
    { id: 'awakened', opponent: 'shadowAwakened', arena: 'crystalMine', aiOffset: 0, next: 'sovereign' },
    {
      id: 'sovereign', opponent: 'sovereign', arena: 'orbital', aiOffset: 0, unlocks: ['sovereign'],
      outcomes: [
        { condition: { type: 'healthRatioAbove', threshold: 0.75 }, next: 'foretold' },
        { condition: { type: 'always' }, ending: 'normal' },
      ],
    },
    { id: 'foretold', opponent: 'foretold', arena: 'sanctuary', aiOffset: 0, secret: true, unlocks: ['foretold'], ending: 'secret' },
  ],
  endings: {
    normal: { unlocks: [] },
    secret: { unlocks: [] },
  },
};
