export const DISPLAY_FONT = 'Oxanium';
const FONT_FAMILY = `${DISPLAY_FONT}, system-ui, sans-serif`;
const MONO_FONT_FAMILY = 'ui-monospace, Consolas, monospace';

export const colors = {
  background: '#05070d',
  floor: '#0d1220',
  floorEdge: '#3a4a6b',
  wall: '#1b2233',
  text: '#e8ecf5',
  textMuted: '#8a94ab',
  accent: '#9fb4d9',
  overlay: 'rgba(0, 0, 0, 0.65)',
  saberHilt: '#b9bec9',
  saberCore: '#ffffff',
  groundShadow: 'rgba(0, 0, 0, 0.45)',
  debug: '#7cfc00',
  debugBackground: 'rgba(0, 0, 0, 0.55)',
  debugBody: 'rgba(124, 252, 0, 0.8)',
  debugInvulnerable: 'rgba(124, 252, 0, 0.25)',
  debugHitbox: 'rgba(255, 80, 80, 0.9)',
  hudHealth: '#e8ecf5',
  hudDanger: '#e5484d',
  hudGhost: 'rgba(232, 236, 245, 0.3)',
  hudStamina: '#8a94ab',
  hudTrack: 'rgba(255, 255, 255, 0.08)',
  desaturateGray: '#808080',
  desaturateDim: '#000000',
  hitFlash: '#ffffff',
  saberFlare: '#ffffff',
  letterbox: '#000000',
  arenaStone: '#1d2430',
  arenaMoon: '#9fb7d9',
  arenaWater: '#0a1622',
  arenaWaterEdge: '#3b5f80',
  arenaRock: '#110d16',
  arenaCrystal: '#2a2140',
  arenaCrystalEdge: '#4d3d70',
  arenaCity: '#0d111c',
  arenaNeon: '#5fd4e6',
  arenaRoof: '#10141f',
  arenaRain: '#9fb4d9',
  arenaPlanet: '#16233a',
  arenaAtmosphere: '#4f7fb8',
  arenaSun: '#e8f0ff',
  arenaWood: '#0c1410',
  arenaMoss: '#0f1a14',
  arenaFungus: '#1f3a30',
  arenaSpore: '#6fe0b0',
};

export const textStyles = {
  touchLabel: { font: `18px ${FONT_FAMILY}`, color: colors.textMuted, align: 'center', baseline: 'middle' },
  touchActive: { font: `18px ${FONT_FAMILY}`, color: colors.text, align: 'center', baseline: 'middle' },
  touchHint: { font: `20px ${FONT_FAMILY}`, color: colors.textMuted, align: 'center', baseline: 'middle' },
  title: {
    font: `bold 88px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'center',
    baseline: 'middle',
    letterSpacing: '18px',
  },
  tagline: {
    font: `22px ${FONT_FAMILY}`,
    color: colors.accent,
    align: 'center',
    baseline: 'middle',
    letterSpacing: '6px',
  },
  heading: {
    font: `bold 48px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'center',
    baseline: 'middle',
  },
  subtitle: {
    font: `28px ${FONT_FAMILY}`,
    color: colors.accent,
    align: 'center',
    baseline: 'middle',
  },
  hint: {
    font: `20px ${FONT_FAMILY}`,
    color: colors.textMuted,
    align: 'center',
    baseline: 'middle',
  },
  message: {
    font: `bold 64px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'center',
    baseline: 'middle',
  },
  menuItem: {
    font: `28px ${FONT_FAMILY}`,
    color: colors.textMuted,
    align: 'center',
    baseline: 'middle',
  },
  menuItemSelected: {
    font: `28px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'center',
    baseline: 'middle',
  },
  hudNameLeft: {
    font: `bold 18px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'left',
    baseline: 'middle',
  },
  hudNameRight: {
    font: `bold 18px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'right',
    baseline: 'middle',
  },
  trainingStatus: {
    font: `18px ${FONT_FAMILY}`,
    color: colors.textMuted, align: 'left', baseline: 'middle',
  },
  accentHint: {
    font: `20px ${FONT_FAMILY}`,
    color: colors.accent,
    align: 'center',
    baseline: 'middle',
  },
  replayLabel: {
    font: `bold 22px ${FONT_FAMILY}`,
    color: colors.accent,
    align: 'left',
    baseline: 'middle',
    letterSpacing: '6px',
  },
  replaySkip: {
    font: `18px ${FONT_FAMILY}`,
    color: colors.textMuted,
    align: 'right',
    baseline: 'middle',
  },
  resultName: {
    font: `bold 22px ${FONT_FAMILY}`,
    color: colors.accent,
    align: 'center',
    baseline: 'middle',
  },
  resultValue: {
    font: `22px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'center',
    baseline: 'middle',
  },
  tableKey: {
    font: `22px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'right',
    baseline: 'middle',
  },
  tableDescription: {
    font: `22px ${FONT_FAMILY}`,
    color: colors.textMuted,
    align: 'left',
    baseline: 'middle',
  },
  tableLabel: {
    font: `22px ${FONT_FAMILY}`,
    color: colors.textMuted,
    align: 'right',
    baseline: 'middle',
  },
  tableValue: {
    font: `22px ${FONT_FAMILY}`,
    color: colors.text,
    align: 'left',
    baseline: 'middle',
  },
  debug: {
    font: `14px ${MONO_FONT_FAMILY}`,
    color: colors.debug,
    align: 'left',
    baseline: 'top',
  },
};
