export const texts = {
  arenas: { refinery: 'Plataforma de Refino', sanctuary: 'Santuário Alagado', crystalMine: 'Mina de Cristal', platform: 'Plataforma de treino' },
  arenaDescriptions: {
    refinery: 'Plataforma industrial suspensa sobre o fosso',
    sanctuary: 'Templo em ruínas sob a lua, sobre a água',
    crystalMine: 'Caverna onde os cristais pegam a cor das lâminas',
  },
  menu: {
    tagline: 'UM DUELO DE LÂMINAS DE ENERGIA',
    duel: 'Duelar',
    training: 'Treino',
    options: 'Opções',
    controls: 'Controles',
    navigation: '{up}  e  {down}  escolher   ·   {confirm}  confirmar',
  },
  options: {
    title: 'OPÇÕES',
    keyboard: 'Teclado: {preset}',
    keyboardPresets: { classic: 'A/D + J/K/L/Shift', arrows: 'Setas + Z/X/C/V' },
    difficulty: 'Dificuldade: {level}',
    effects: 'Efeitos: {value}',
    sound: 'Som: {value}',
    music: 'Música: {value}',
    back: 'Voltar',
    full: 'Completos',
    reduced: 'Reduzidos',
    on: 'Ligado',
    off: 'Desligado',
    onFeminine: 'Ligada',
    offFeminine: 'Desligada',
  },
  controls: {
    title: 'CONTROLES',
    or: ' ou ',
    back: '{back}  voltar',
    gamepad: 'Controle: direcional mover · A pular · X rápido · Y forte · LB/LT guarda · B esquiva · RB/RT habilidade · Start pausa · A confirmar',
    actions: {
      moveLeft: 'Mover para a esquerda',
      moveRight: 'Mover para a direita',
      jump: 'Pular',
      lightAttack: 'Ataque rápido',
      heavyAttack: 'Ataque forte',
      forwardHeavy: 'Forte de avanço (para a frente)',
      airAttack: 'Ataque aéreo (durante o pulo)',
      block: 'Bloquear (segurar)',
      parry: 'Aparar (tocar na hora do golpe)',
      riposte: 'Riposta (ataque rápido depois de aparar)',
      shove: 'Empurrar (quebra a defesa)',
      special: 'Habilidade do personagem',
      dodge: 'Esquivar',
      pause: 'Pausar',
      toggleDebug: 'Debug',
      recordDummy: 'Treino: gravar inputs',
      playDummy: 'Treino: reproduzir no boneco',
      trainingHitboxes: 'Treino: hitboxes',
    },
  },
  duel: {
    intro: 'ROUND {number}',
    finalRound: 'ROUND FINAL',
    knockout: 'K.O.',
    pauseHint: '{pause}  pausar',
  },
  characterSelect: {
    titles: { player: 'ESCOLHA SEU LUTADOR', opponent: 'ESCOLHA O ADVERSÁRIO', arena: 'ESCOLHA A ARENA' },
    footer: '{up}  e  {down}  escolher · {confirm}  confirmar · {back}  voltar',
  },
  training: {
    inputs: 'Jogador: {player}   ·   Boneco: {dummy}',
    recorder: '{mode} · {seconds} s',
    recorderModes: { idle: 'Gravação parada', recording: 'Gravando', playing: 'Reproduzindo' },
    inputNames: { idle: '—', left: '←', right: '→', jump: 'pulo', lightAttack: 'rápido', heavyAttack: 'forte', block: 'guarda', dodge: 'esquiva', special: 'habilidade' },
    frameData: '{attack} · {result} · {advantage} s',
    attacks: { air: 'Aéreo', forwardHeavy: 'Forte de avanço', light: 'Rápido', light2: 'Rápido 2', light3: 'Rápido 3', light4: 'Rápido 4', light5: 'Rápido 5', heavy: 'Forte', riposte: 'Riposta', shove: 'Empurrão', special: 'Habilidade' },
    results: {
      hit: 'acertou',
      block: 'bloqueado',
      parry: 'aparado',
      perfectParry: 'aparado perfeitamente',
      guardBreak: 'quebrou a guarda',
      shove: 'desequilibrou',
      counter: 'contra-atacado',
    },
  },
  pause: {
    title: 'PAUSADO',
    resume: 'Continuar',
    restart: 'Reiniciar duelo',
    quit: 'Sair para o menu',
  },
  result: {
    victory: 'VITÓRIA',
    defeat: 'DERROTA',
    winner: '{name} venceu o duelo',
    stats: 'Tempo  {time} s   ·   Golpes acertados  {hits}   ·   Defesas  {blocks}',
    defenseStats: 'Parries  {parries}   ·   Perfeitos  {perfectParries}   ·   Quebras de guarda  {guardBreaks}',
    rematch: 'Revanche',
    menu: 'Menu principal',
  },
};

export const difficultyNames = {
  easy: 'Fácil',
  normal: 'Normal',
  hard: 'Difícil',
};

export const controlsScreenRows = [
  { label: 'moveLeft', actions: ['moveLeft'] },
  { label: 'moveRight', actions: ['moveRight'] },
  { label: 'jump', actions: ['jump'] },
  { label: 'lightAttack', actions: ['lightAttack'] },
  { label: 'heavyAttack', actions: ['heavyAttack'] },
  { label: 'forwardHeavy', groups: [['moveLeft', 'moveRight'], ['heavyAttack']] },
  { label: 'airAttack', groups: [['lightAttack', 'heavyAttack']] },
  { label: 'block', actions: ['block'] },
  { label: 'parry', actions: ['block'] },
  { label: 'riposte', actions: ['lightAttack'] },
  { label: 'shove', actions: ['block', 'lightAttack'] },
  { label: 'dodge', actions: ['dodge'] },
  { label: 'special', actions: ['special'] },
  { label: 'pause', actions: ['pause'] },
  { label: 'toggleDebug', actions: ['toggleDebug'] },
  { label: 'recordDummy', actions: ['recordDummy'] },
  { label: 'playDummy', actions: ['playDummy'] },
  { label: 'trainingHitboxes', actions: ['trainingHitboxes'] },
];

export const keyComboSeparator = '  +  ';

export const layout = {
  menu: {
    titleY: 210,
    taglineY: 278,
    firstItemY: 370,
    itemSpacing: 52,
    footerY: 660,
  },
  characterSelect: {
    titleY: 110,
    listX: 380,
    firstItemY: 230,
    itemSpacing: 58,
    previewX: 880,
    previewY: 590,
    previewScale: 1.3,
    infoY: 200,
    infoLineSpacing: 36,
    arenaPreviewY: 260,
    arenaPreviewScale: 0.42,
    footerY: 670,
  },
  menuList: {
    markerWidth: 18,
    markerGap: 16,
    markerThickness: 2,
  },
  options: {
    titleY: 180,
    firstItemY: 300,
    itemSpacing: 52,
  },
  controls: {
    titleY: 110,
    firstRowY: 150,
    rowSpacing: 27,
    columnGap: 16,
    gamepadY: 624,
    footerY: 670,
  },
  pause: {
    titleY: 250,
    firstItemY: 340,
    itemSpacing: 52,
  },
  result: {
    titleY: 210,
    winnerY: 275,
    statsY: 320,
    defenseStatsY: 354,
    firstItemY: 420,
    itemSpacing: 52,
  },
  hud: {
    margin: 40,
    nameY: 32,
    healthY: 48,
    healthWidth: 440,
    healthHeight: 10,
    staminaGap: 6,
    staminaHeight: 4,
    ghostDelay: 0.4,
    ghostSpeed: 0.6,
    lowHealthRatio: 0.25,
    lowHealthBlinkPeriod: 0.8,
    lowHealthDimAlpha: 0.45,
    rejectFlashDuration: 0.3,
    rejectBlinkPeriod: 0.1,
    inputsY: 634,
    recorderY: 690,
    frameDataY: 660,
    roundY: 80,
    roundSize: 8,
    roundGap: 6,
    pauseHintY: 690,
  },
  letterbox: {
    height: 64,
    speed: 3.5,
    perfectParryAmount: 0.5,
    perfectParryDuration: 0.35,
  },
  ignition: {
    delay: 0.25,
    duration: 0.35,
  },
  messages: {
    y: 300,
    introDuration: 1,
    knockoutDuration: 1.2,
    fadeTime: 0.3,
  },
};
