export const SoundName = Object.freeze({
  SWING_LIGHT: 'swingLight',
  SWING_HEAVY: 'swingHeavy',
  HIT: 'hit',
  HEAVY_HIT: 'heavyHit',
  BLOCK: 'block',
  GUARD_BREAK: 'guardBreak',
  CLASH: 'clash',
  DEATH: 'death',
  DODGE: 'dodge',
  DENIED: 'denied',
  PARRY: 'parry',
  PERFECT_PARRY: 'perfectParry',
  SHOVE: 'shove',
  IGNITE: 'ignite',
  HEARTBEAT: 'heartbeat',
  FEINT: 'feint',
  UI_MOVE: 'uiMove',
  UI_CONFIRM: 'uiConfirm',
});
